### PR TITLE
Explicitly naming column names in update to `_versions_links`

### LINKED ISSUE #45: Incorrect sql query in core-api.js
### Hello 👋

The original query was
`INSERT INTO ${model.collectionName}_versions_links VALUES (${version},${result.id})` and I had a problem creating a new version I kept getting a 500 error from the server, eventually changing query to node_modules/@notum-cz/strapi-plugin-content-versioning/server/services/core-api.js for `INSERT INTO ${model.collectionName}_versions_links (post_id, inv_post_id) VALUES (${version}, ${result.id})` helped.

### PR DESCRIPTION
**Pull request by lundcm**
Fixes #45 with more explicit SQL

@martincapek does this look like better SQL and a small enough change to get merged in? Thank you

### CODE REVIEW

**Comment by martincapek** [comment]
Hi, I will take a look and merge it :)

**Comment by RicardoCruzXID** [comment]
This change has a bug
https://github.com/notum-cz/strapi-plugin-content-versioning/issues/46#issuecomment-1279686790

when the content-type name contains ‘-' e.g: 'type-demo' , it will give error.
`error: INSERT INTO type_demos_versions_links (type-demo_id, inv_type-demo_id) VALUES (1,2) - syntax error at or near "-" error: INSERT INTO type_demos_versions_links (type-demo_id, inv_type-demo_id) VALUES (1,2) - syntax error at or near "-"`

**Review by martincapek — APPROVED** [review]

**Comment by martincapek** [comment]
It is working, I will fix conflict and merge it :) Thanks! :)

**Comment by martincapek** [comment]
Already merged

**Pull request closed without merging**
