### PR TITLE
Remove timestamp values for new versions

### PR DESCRIPTION
**Pull request by Fikoun**
closes: #67

### CODE REVIEW

**Comment by tasola** [comment]
Thank you @Fikoun, I appreciate it!
@martincapek Please have a look at this :)

**Comment by tasola** [comment]
@martincapek I'm still really interested in seeing this getting released

**Comment by RickardssonJ** [comment]
If this could be reviewed and released it would be great!
@martincapek

**Comment by tasola** [comment]
@martincapek

**Review by omikulcik — APPROVED** [review]

**Comment by omikulcik** [comment]
Hi @tasola, @RickardssonJ I am now maintaining this repo. We appreciate your engagement. I've just merged the PR and we will publish new version on NPM soon.

**Comment by RickardssonJ** [comment]
Thank you @omikulcik !

**Pull request merged**
