### PR TITLE
Feature/localization + cloning

### PR DESCRIPTION
**Pull request by Fikoun**
### Third phase of locale versioning support
- Support for multiple locales with versioning
- Cloning support (requires patch *see README.md)
- Migration when plugin enables/disables 
- ! New versioning implementation is **NOT backward compatible** with the previous, as it is in early development

_closes: #58 
closes: #12_

### CODE REVIEW

**Comment by jmdrawneek** [comment]
Great working @Fikoun - what's left to do?

**Comment by martincapek** [comment]
H @jmdrawneek, I believe just resolve the conflict (I will do it) and then test it. And we can merge it :)

**Comment by jmdrawneek** [comment]
Hmm I just gave it a go and got this error:
```
ERROR:  column t0.locale does not exist at character 74
STATEMENT:  select "t0"."id", "t0"."vuid", "t0"."version_number", "t0"."created_at", "t0"."locale" from "public"."landing_pages" as "t0" where ("t0"."vuid" = $1 and "t0"."published_at" is not null) limit $2
benzac-cms       | [2022-12-01 11:04:18.393] error: select "t0"."id", "t0"."vuid", "t0"."version_number", "t0"."created_at", "t0"."locale" from "public"."landing_pages" as "t0" where ("t0"."vuid" = $1 and "t0"."published_at" is not null) limit $2 - column t0.locale does not exist
benzac-cms       | error: select "t0"."id", "t0"."vuid", "t0"."version_number", "t0"."created_at", "t0"."locale" from "public"."landing_pages" as "t0" where ("t0"."vuid" = $1 and "t0"."published_at" is not null) limit $2 - column t0.locale does not exist
````

Have I missed something?

**Comment by tasola** [comment]
@Fikoun Any news on this PR? I'm eager to use this plugin with I18N content

**Comment by Fikoun** [comment]
We are working on updates so the plugin is working smoothly. It will by implemented in following weeks so it can fit with the new Strapi changes.

**Pull request merged**
